In [1]:
#1. Create a null vector of size 10 but the fifth value which is 1. 
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
#2. Create a vector with values ranging from 10 to 49.
v=np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0,9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)


In [16]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
array = np.random.rand(10, 10)

# Find the minimum and maximum values in the array
min_value = array.min()
max_value = array.max()

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.0021056219285037203
Maximum value: 0.9786710258826377


In [21]:
#6. Create a random vector of size 30 and find the mean value.
random=np.random.randint(10,30,30)
print(random)
print("mean:",random.mean())

[21 26 26 27 12 20 24 20 16 22 29 23 12 16 29 25 20 20 21 13 17 28 16 14
 18 22 12 14 16 23]
mean: 20.066666666666666
